openapi: 3.0.1
info:
  title: Card creation API
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/IVANPINTAR95_1/card-creation_api/1.0.0
  - url: https://api.something.com/v1

paths:
  /api/v1/card-request:
    post:
      tags:
        - new-card-request
      summary: Create new card
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/NewCardRequest'
        required: true
      responses:
        201:
          description: New card request successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                message: "New card request successfully created."
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "400"
                id: "bad-request-001"
                description: "Invalid request format or data."
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "401"
                id: "unauthorized-002"
                description: "Authorization required."
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "404"
                id: "not-found-003"
                description: "Resource not found."
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "500"
                id: "internal-error-004"
                description: "An unexpected error occurred."

components:
  schemas:
    NewCardRequest:
      title: Card request
      type: object
      properties:
        firstName:
          type: string
          minLength: 2
          maxLength: 50
          description: First name must be between 2 and 50 characters.
        lastName:
          type: string
          minLength: 2
          maxLength: 50
          description: Last name must be between 2 and 50 characters.
        status:
          type: string
          minLength: 3
          maxLength: 50
          description: Status must be between 3 and 50 characters.
        oib:
          type: string
          pattern: '^\d{11}$'
          description: OIB must consist of exactly 11 digits.
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Optional error code for reporting purposes
        id:
          type: string
          description: Unique identifier for audit purposes
        description:
          type: string
          description: The description of the error
    Response:
      title: Response
      type: object
      properties:
        message:
          type: string
          description: The message returned in the response